Molavi/urls.py
from django.urls import path
from . import views


app_name = 'Molavi'

urlpatterns = [
    #/categories/
    path('categories/', views.categories,name='categories'),
    #categories/id/
    path('categories/<int:question_id>/', views.all_details, name='all_details'),
    path('categories/<int:question_id>/results', views.results, name='results'),




]

molavi/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Molavi.urls')),

]

Molavi/models.py
from django.db import models


class categories(models.Model):
    categories_name = models.CharField(max_length=300)

    def __str__(self):
        return self.categories_name


class raftar_mosbat(models.Model):
    category = models.ForeignKey(categories, on_delete=models.CASCADE)
    title = models.CharField(max_length=300, null=True)

    def __str__(self):
        return self.title + ' categoy: {} '.format(self.category)


class raftar_manfi(models.Model):
    category = models.ForeignKey(categories, on_delete=models.CASCADE)
    title = models.CharField(max_length=300, null=True)

    def __str__(self):
        return self.title + ' categoy: {} '.format(self.category)


class jameh(models.Model):
    category = models.ForeignKey(categories, on_delete=models.CASCADE)
    title = models.CharField(max_length=300, null=True)

    def __str__(self):
        return self.title + ' categoy: {} '.format(self.category)


class elm_o_andisheh(models.Model):
    category = models.ForeignKey(categories, on_delete=models.CASCADE)
    title = models.CharField(max_length=300, null=True)

    def __str__(self):
        return self.title + ' categoy: {} '.format(self.category)


class jahl(models.Model):
    category = models.ForeignKey(categories, on_delete=models.CASCADE)
    title = models.CharField(max_length=300, null=True)

    def __str__(self):
        return self.title + ' categoy: {} '.format(self.category)


class ghodrat(models.Model):
    category = models.ForeignKey(categories, on_delete=models.CASCADE)
    title = models.CharField(max_length=300, null=True)

    def __str__(self):
        return self.title + ' categoy: {} '.format(self.category)


class nezame_tabieye_donya(models.Model):
    category = models.ForeignKey(categories, on_delete=models.CASCADE)
    title = models.CharField(max_length=300, null=True)

    def __str__(self):
        return self.title + ' categoy: {} '.format(self.category)



class masnavi_manavi(models.Model):
    category = models.ForeignKey(categories, on_delete=models.CASCADE)
    title = models.CharField(max_length=300, null=True)

    def __str__(self):
        return self.title + ' categoy: {} '.format(self.category)


class zamimeh(models.Model):
    category = models.ForeignKey(categories, on_delete=models.CASCADE)
    title = models.CharField(max_length=300, null=True)

    def __str__(self):
        return self.title + ' categoy: {} '.format(self.category)

Molavi/views.py
from django.shortcuts import render, get_object_or_404
from . import models


def categories(request):
    categories = models.categories.objects.all()
    return render(request, 'Molavi/categories.html', {'categories': categories})


def all_details(request, question_id):
    categories_raftare_manfi = get_object_or_404(models.categories, pk=question_id)
    categories_raftare_mosbat = get_object_or_404(models.categories,pk=question_id)
    categories_jameh = get_object_or_404(models.categories,pk=question_id)
    return render(request, 'Molavi/raftare_manfi.html', {'categories_raftare_manfi': categories_raftare_manfi,
                                                         'categories_raftare_mosbat':categories_raftare_mosbat,
                                                         'categories_jameh' : categories_jameh,
                                                         })


def results(request,question_id):
   test = models.raftar_manfi.objects.filter(title='مقدمه ای بر رفتار منفی',pk=question_id)
   test2 = models.raftar_manfi.objects.filter(title='آزمندی',pk=question_id)
   test3 = models.raftar_manfi.objects.filter(title='بخل', pk=question_id)
   return render(request, 'Molavi/results.html', {'test':test,'test2':test2,'test3':test3})

Molavi/templates/Molavi/categories.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% for all in categories %}
      <a href="{% url 'Molavi:all_details' all.id %}">{{ all }}
      </a><br>
{% endfor %}

</body>
</html>

Molavi/templates/Molavi/jameh.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body dir = 'rtl'>
</body>
</html>

Molavi/templates/Molavi/raftare_manfi.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
     {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">
</head>
<body>
{% if categories_raftare_manfi.raftar_manfi_set.all %}
{% for raftare_manfi in categories_raftare_manfi.raftar_manfi_set.all %}
    <a href="{% url 'Molavi:results' raftare_manfi.id %}">{{ raftare_manfi.title }}</a>
    <br>

{% endfor %}
{% elif categories_raftare_mosbat.raftar_mosbat_set.all %}
   {% for raftare_mosbat in categories_raftare_mosbat.raftar_mosbat_set.all %}
       {{ raftare_mosbat.title }}<br>
    {% endfor %}
{% elif categories_jameh.jameh_set.all %}
    {% for jameh in categories_jameh.jameh_set.all %}
        {{ jameh.title }}<br>
    {% endfor %}
{% endif %}


</body>
</html>

Molavi/templates/Molavi/results.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% if test %}
        مقدمه بر رفتار منفی
{% elif test2 %}
    آزمندی
{% elif test3 %}
    بخل
{% endif %}
</body>
</html>